### ISSUE TITLE
Does this plugin still work?

### ISSUE THREAD

**Issue by SheepCommander** [LandenStephenss/PowerFiles#3]
I saw that it seems this is supposed to view SVG and PDF

without plugin
![image](https://user-images.githubusercontent.com/66646514/148704194-3f11654a-0164-4bce-965d-267c5dd4cc87.png)

with plugin
![image](https://user-images.githubusercontent.com/66646514/148704223-c747c817-8274-4ef9-b469-6d5bded8cce6.png)

![image](https://user-images.githubusercontent.com/66646514/148704245-0ef274b8-9870-41b2-bb43-9bc9b84a8fd6.png)

![image](https://user-images.githubusercontent.com/66646514/148704235-13f755d2-e837-48f5-a3d5-0b7841865267.png)

**Comment by LandenStephenss** [comment]
It only works with SVG, as long as you send a valid SVG then it should work.

**Comment by SheepCommander** [comment]
Guess my SVG was just invalid, it does work. Thanks!
![image](https://user-images.githubusercontent.com/66646514/149853412-c30eea4e-22a2-4abd-8ada-8ba378a18adc.png)
